services:
  - type: web
    name: domain-value-estimator
    env: node
    buildCommand: npm install && npm run build
    startCommand: node api/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_APP_URL
        sync: false
      - key: VITE_OPENAI_API_KEY
        sync: false
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: VITE_STRIPE_SECRET_KEY
        sync: false
      - key: VITE_STRIPE_PRICE_ID
        sync: false
      - key: VITE_STRIPE_WEBHOOK_SECRET
        sync: false
      - key: SMTP_HOST
        value: smtp.sendgrid.net
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: apikey
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        value: noreply@domainvalue.dev